UPDATE exercises e SET gif_url = v.url, image_url = v.url, updated_at = now()
FROM (VALUES
('push-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0662.gif'),
('wide-push-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1311.gif'),
('diamond-push-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0283.gif'),
('incline-push-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0493.gif'),
('decline-push-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0279.gif'),
('bodyweight-squat','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3119.gif'),
('jump-squat','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0514.gif'),
('lunge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3470.gif'),
('reverse-lunge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0078.gif'),
('walking-lunge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1460.gif'),
('glute-bridge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3561.gif'),
('single-leg-glute-bridge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3561.gif'),
('plank','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0464.gif'),
('side-plank','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1775.gif'),
('mountain-climber','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0630.gif'),
('burpee','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1160.gif'),
('jumping-jack','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3223.gif'),
('high-knees','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3636.gif'),
('bear-crawl','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3360.gif'),
('inchworm','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1471.gif'),
('superman','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0803.gif'),
('bird-dog','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0276.gif'),
('dead-bug','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0276.gif'),
('crunch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0274.gif'),
('bicycle-crunch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0972.gif'),
('leg-raise','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0620.gif'),
('russian-twist','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0687.gif'),
('v-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1014.gif'),
('wall-sit','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3119.gif'),
('calf-raise','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1372.gif'),
('tricep-dip','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0814.gif'),
('pike-push-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1296.gif'),
('pull-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0652.gif'),
('chin-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1326.gif'),
('goblet-squat','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0534.gif'),
('dumbbell-squat','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0413.gif'),
('dumbbell-lunge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0336.gif'),
('romanian-deadlift','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1459.gif'),
('dumbbell-deadlift','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0300.gif'),
('dumbbell-row','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0293.gif'),
('bent-over-row','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0027.gif'),
('dumbbell-press','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0289.gif'),
('dumbbell-shoulder-press','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0405.gif'),
('lateral-raise','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0334.gif'),
('front-raise','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0310.gif'),
('bicep-curl','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1651.gif'),
('hammer-curl','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0313.gif'),
('tricep-kickback','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0333.gif'),
('overhead-tricep-extension','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0430.gif'),
('barbell-squat','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0043.gif'),
('barbell-deadlift','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0032.gif'),
('barbell-bench-press','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0025.gif'),
('barbell-shoulder-press','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0091.gif'),
('hip-thrust','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1409.gif'),
('kettlebell-swing','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0549.gif'),
('kettlebell-goblet-squat','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0534.gif'),
('cable-row','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0861.gif'),
('lat-pulldown','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0198.gif'),
('leg-press','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0739.gif'),
('leg-curl','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0586.gif'),
('leg-extension','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0585.gif'),
('hundred','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0274.gif'),
('roll-up','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1014.gif'),
('single-leg-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0972.gif'),
('double-leg-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0620.gif'),
('scissors','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0459.gif'),
('teaser','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1014.gif'),
('swimming','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0803.gif'),
('swan','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1366.gif'),
('mermaid','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1775.gif'),
('clam','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3006.gif'),
('pilates-bridge','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3561.gif'),
('spine-twist','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0687.gif'),
('saw','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0547.gif'),
('leg-circle','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0620.gif'),
('plank-leg-lift','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0464.gif'),
('cat-cow','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0803.gif'),
('child-pose','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1511.gif'),
('downward-dog','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1471.gif'),
('worlds-greatest-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1604.gif'),
('hip-flexor-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1559.gif'),
('hamstring-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1511.gif'),
('shoulder-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1271.gif'),
('thoracic-rotation','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0687.gif'),
('figure-four-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1559.gif'),
('neck-stretch','https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0716.gif')
) AS v(slug, url)
WHERE e.slug = v.slug;

UPDATE workouts w SET cover_image_url = sub.gif
FROM (
  SELECT we.workout_id, e.gif_url AS gif
  FROM workout_exercises we
  JOIN exercises e ON e.id = we.exercise_id
  WHERE we.order_index = 0
) sub
WHERE w.id = sub.workout_id AND w.is_builtin = true;
